language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.composer/cache